language: node_js
node_js:
  - 10.15.2

install: 
  - "npm install"
    
script:
  - "npm run test"

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key: 
    secure: "$HEROKU_API_KEY"
  app: simpleattendance-api
  on: 
    repo: laudb/simple-attendance

services:
  - mongodb